---
simpleId: loa1-rp
translations:
  - locale: en
    name: register for an LOA1 identity profile
    rpName: LOA1 RP
    analyticsDescription: analytics description for loa1-test-rp
    otherWaysText: If you can’t verify your identity using GOV.UK Verify, there are other ways to <a href='http://www.example.com'>register for an LOA1 identity profile</a>
    otherWaysDescription: other ways to register for an LOA1 identity profile
    tailoredText: <p>This is tailored text for LOA1 RP</p>
    taxonName: Benefits
