---
simpleId: loa2-loa1-test-rp
translations:
  - locale: en
    name: register for an LOA2 or LOA1 identity profile
    rpName: LOA2 LOA1 Test RP
    analyticsDescription: analytics description for loa2-loa1-test-rp
    otherWaysText: If you can’t verify your identity using GOV.UK Verify, there are other ways to <a href='http://www.example.com'>register for an LOA2 or LOA1 identity profile</a>
    otherWaysDescription: other ways to register for an LOA2/LOA1 identity profile
    tailoredText: <p>This is tailored text for LOA2 LOA1 TEST RP</p>
    taxonName: Benefits