---
simpleId: test-rp-non-eidas
translations:
  - locale: en
    name: test GOV.UK Verify user journeys
    rpName: Test RP
    analyticsDescription: analytics description for test-rp-non-eidas
    otherWaysText: |
      <p>If you can’t verify your identity using GOV.UK Verify, you can test GOV.UK Verify user journeys <a href="http://www.example.com">here</a>.</p>
      <p>Tell us your:</p>
      <ul>
       <li>name</li>
       <li>age</li>
      </ul>
      <p>Include any other relevant details if you have them.</p>
    otherWaysDescription: test GOV.UK Verify user journeys
    tailoredText: <p>This is tailored text for test-rp</p>
    taxonName: Benefits
