version: '3.5'

services:
  config:
    image: ${CONFIG_IMAGE}
    env_file:
      - urls.env
    environment:
      APP_NAME: config
    volumes:
      - ./data:/app/data:ro

  policy:
    image: ${POLICY_IMAGE}
    env_file:
      - urls.env
    environment:
      APP_NAME: policy
    volumes:
      - ./data:/app/data:ro

  saml-engine:
    image: ${SAML_ENGINE_IMAGE} 
    env_file:
      - urls.env
    environment:
      APP_NAME: saml-engine
    volumes:
      - ./data:/app/data:ro

  saml-proxy:
    image: ${SAML_PROXY_IMAGE}
    env_file:
      - urls.env
    environment:
      APP_NAME: saml-proxy
    volumes:
      - ./data:/app/data:ro

  saml-soap-proxy:
    image: ${SAML_SOAP_PROXY_IMAGE}
    env_file:
      - urls.env
    environment:
      APP_NAME: saml-soap-proxy
    volumes:
      - ./data:/app/data:ro

  stub-event-sink:
    image: ${STUB_EVENT_SINK_IMAGE}
    environment:
      APP_NAME: stub-event-sink
    volumes:
      - ./data:/app/data:ro

  frontend:
    image: ${FRONTEND_IMAGE}
    env_file:
      - configuration/frontend.env
    environment:
      CONFIG_API_HOST: ${CONFIG_URL}
      POLICY_HOST: ${POLICY_URL}
      SAML_PROXY_HOST: ${SAML_PROXY_URL}
    volumes:
      - ./configuration/stub-frontend-fed-config:/fed-config:ro

  metadata:
    image: nginx
    volumes:
      - ./data/metadata:/usr/share/nginx/html:ro

  metadata-aggregator:
    image: ${AGGREGATOR_IMAGE}

  stub-idp:
    image: ${STUB_IDP_IMAGE}
    depends_on:
      - stub-idp-db
    volumes:
      - ./data:/app/data:ro
      - ../verify-stub-idp/build/resources/main/assets:/assets:ro
      - ./configuration/idps:/idps:ro
    env_file:
      - urls.env
      - stub-idp.env
    environment:
      PORT: 80
      LOG_PATH: /app/logs
      GRAPHITE_REPORTING_FREQUENCY: 24h
      STUB_IDP_BASIC_AUTH: "false"
      STUB_IDPS_FILE_PATH: /idps/stub-idps.yml
      ENTITY_ID: http://%s.local/SSO/POST
      STUB_IDP_ASSET_LOCATION: /assets
      STUB_IDP_YAML_FILE_LOCATION: /idps/stub-idps.yml
      STUB_IDP_HOSTNAME: ${STUB_IDP_URL}

  msa:
    image: ${MSA_IMAGE}
    volumes:
      - ./data:/app/data:ro
    env_file:
      - urls.env
    environment:
      MSA_ENTITY_ID: http://test-rp-ms.local/SAML2/MD
      ASSERTION_CONSUMER_SERVICE_URL: ${TEST_RP_URL}/matching-service/POST
      LMS_MATCH_URL: ${TEST_RP_URL}/test-rp/matching-service/POST
      LMS_UAC_URL: ${TEST_RP_URL}/test-rp/unknown-user/POST
      HUB_SSO_URL: ${FRONTEND_URL}/SAML2/SSO
      EUROPEAN_IDENTITY_ENABLED: "true"

  test-rp:
    image: ${TEST_RP_IMAGE}
    volumes:
      - ../verify-test-rp/build/resources/main/assets:/assets:ro
    env_file:
      - urls.env
      - test-rp.env
    environment:
      TEST_RP_ASSETS_LOCATION: /assets
      TEST_RP_PORT: 80
      LOG_PATH: /app/logs
      TEST_RP_PRIVATE_BETA_USER_ACCESS_RESTRICTION_ENABLED: "false"
      TEST_RP_ENTITY_ID: http://%s.local/SAML2/MD
      MSA_ENTITY_ID: http://test-rp-ms.local/SAML2/MD
      MSA_METADATA_URL: ${MSA_URL}/matching-service/SAML2/metadata

  stub-idp-db:
    image: postgres
