version: '3'

services:
  config:
    build:
      context: .
      dockerfile: Dockerfiles/hub-app
      args:
        config_location: configuration/hub/config.yml
        app_name: config
    env_file:
      - .env
    environment:
      APP_NAME: config
    volumes:
      - ./data:/app/data:ro

  policy:
    build:
      context: .
      dockerfile: Dockerfiles/hub-app
      args:
        config_location: configuration/hub/policy.yml
        app_name: policy
    env_file:
      - .env
    environment:
      APP_NAME: policy
    volumes:
      - ./data:/app/data:ro

  saml-engine:
    build:
      context: .
      dockerfile: Dockerfiles/hub-app
      args:
        config_location: configuration/hub/saml-engine.yml
        app_name: saml-engine
    env_file:
      - .env
    environment:
      APP_NAME: saml-engine
    volumes:
      - ./data:/app/data:ro

  saml-proxy:
    build:
      context: .
      dockerfile: Dockerfiles/hub-app
      args:
        config_location: configuration/hub/saml-proxy.yml
        app_name: saml-proxy
    env_file:
      - .env
    environment:
      APP_NAME: saml-proxy
    volumes:
      - ./data:/app/data:ro

  saml-soap-proxy:
    build:
      context: .
      dockerfile: Dockerfiles/hub-app
      args:
        config_location: configuration/hub/saml-soap-proxy.yml
        app_name: saml-soap-proxy
    env_file:
      - .env
    environment:
      APP_NAME: saml-soap-proxy
    volumes:
      - ./data:/app/data:ro

  stub-event-sink:
    build:
      context: .
      dockerfile: Dockerfiles/hub-app
      args:
        config_location: configuration/hub/stub-event-sink.yml
        app_name: stub-event-sink
    environment:
      APP_NAME: stub-event-sink
    volumes:
      - ./data:/app/data:ro

  frontend:
    build:
      context: .
      dockerfile: Dockerfiles/frontend
    ports:
      - "${FRONTEND_EXTERNAL_PORT}:80"
    volumes:
      - ../verify-frontend/:/verify-frontend/:rw
    env_file:
      - configuration/frontend.env
    environment:
      CONFIG_API_HOST: ${CONFIG_URL}
      POLICY_HOST: ${POLICY_URL}
      SAML_PROXY_HOST: ${SAML_PROXY_URL}

  metadata:
    image: nginx
    volumes:
      - ./data/metadata:/usr/share/nginx/html:ro

  stub-idp:
    build:
      context: .
      dockerfile: Dockerfiles/stub-idp
    ports:
      - "${STUB_IDP_EXTERNAL_PORT}:80"
    volumes:
      - ./data:/ida-stub-idp/data:ro
      - ../ida-stub-idp/build/resources/main/assets:/assets:ro
      - ./configuration/idps:/idps:ro
    env_file:
      - .env
    environment:
      STUB_IDP_ASSET_LOCATION: /assets
      STUB_IDP_YAML_FILE_LOCATION: /idps/stub-idps.yml

  msa:
    build:
      context: .
      dockerfile: Dockerfiles/msa
    volumes:
      - ./data:/verify-matching-service-adapter-691/data:ro
    env_file:
      - .env
    environment:
      ASSERTION_CONSUMER_SERVICE_URL: ${TEST_RP_URL}/matching-service/POST
      LMS_MATCH_URL: ${TEST_RP_URL}/test-rp/matching-service/POST
      LMS_UAC_URL: ${TEST_RP_URL}/test-rp/unknown-user/POST
      HUB_SSO_URL: http://localhost:${FRONTEND_EXTERNAL_PORT}/SAML2/SSO

  test-rp:
    build:
      context: .
      dockerfile: Dockerfiles/test-rp
    ports:
      - "${TEST_RP_EXTERNAL_PORT}:80"
    volumes:
      - ../ida-sample-rp/build/resources/main/assets:/assets:ro
    env_file:
      - .env
      - test-rp.env
    environment:
      TEST_RP_ASSETS_LOCATION: /assets
      MSA_METADATA_URL: ${MSA_URL}/matching-service/SAML2/metadata
