pki:
  # Format
  # =======================================
  # ca-name:
  #   common-name: Some Root CA Common Name
  #   cert-file: ca-root
  #   intermediates:
  #     intermediate-name:
  #       common-name: Some Intermediate Common Name (Optional - defaults to Verify Local Startup {Intermediate Name} Intermediate CA)
  #       cert-file: ca-intermediate (Optional - defaults to {ca-name}-{intermediate-name})
  #       certs:
  #         cert-name:
  #           type: [signing|encryption]
  #           common-name: Some Cert Common Name (Optional - defaults to Verify Local Startup {Cert Name})
  #           cert-file: ca-intermediate (Optional - defaults to {cert-name})
  verify:
    common-name: Verify Local Startup Root CA
    cert-file: verify-root
    intermediates:
      hub:
        certs:
          hub_signing_primary:
            type: signing
          hub_encryption_primary:
            type: encryption
          hub_signing_secondary:
            type: signing
          hub_encryption_secondary:
            type: encryption

      idp:
        certs:
          stub_idp_signing_primary:
            type: signing
          stub_idp_signing_secondary:
            type: signing

      rp:
        certs:
          sample_rp_signing_primary:
            type: signing
          sample_rp_encryption_primary:
            type: encryption
          sample_rp_signing_secondary:
            type: signing
          sample_rp_encryption_secondary:
            type: encryption
          sample_rp_msa_signing_primary:
            type: signing
          sample_rp_msa_encryption_primary:
            type: encryption
          sample_rp_msa_signing_secondary:
            type: signing
          sample_rp_msa_encryption_secondary:
            type: encryption

      metadata:
        certs:
          metadata_signing_a:
            type: signing
          metadata_signing_b:
            type: signing

# Format
# ================
# truststores:
#   truststore-name:
#     certs:
#       - ca-name
#       - ca-name.intermediates.intermediate-name (JSON selectors from pki section above)
truststores:
  hub:
    certs:
      - verify
      - verify.intermediates.hub
      - verify.intermediates.idp
  hub_federation:
    certs:
      - verify
      - verify.intermediates.hub
  idp_federation:
    certs:
      - verify
      - verify.intermediates.idp
  relying_parties:
    certs:
      - verify
      - verify.intermediates.rp
  metadata:
    certs:
      - verify
      - verify.intermediates.metadata

# Format
# =========
# metadata:
#   hub:
#     signing: ca-name.intermediates.inter-name.certs.signing-cert
#     encryption: ca-name.intermediates.inter-name.certs.encryption-cert
#   idps:
#     signing: ca-name.intermediates.inter-name.certs.encryption-cert
metadata:
  signature: verify.intermediates.metadata.certs.metadata_signing_a
  hub:
    signing: verify.intermediates.hub.certs.hub_signing_primary
    encryption: verify.intermediates.hub.certs.hub_encryption_primary
  idps:
    signing: verify.intermediates.idp.certs.stub_idp_signing_primary
