server:
  applicationConnectors:
    - type: http
      port: ${CONFIG_PORT}
  adminConnectors:
    - type: http
      port: 50241
  requestLog:
    appenders:
      - type: console


logging:
  level: INFO
  appenders:
    - type: console

serviceInfo:
  name: config

rootDataDirectory: data/stub-fed-config

clientTrustStoreConfiguration:
  path: data/pki/hub.ts
  password: marshmallow

rpTrustStoreConfiguration:
  path: data/pki/relying_parties.ts
  password: marshmallow
